#tag::info[]
openapi: 3.0.0 # <1>
info: # <2>
  description: This is a library API
  version: 1.0.0
  title: Library
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags: # <3>
  - name: books
    description: Search for books and add new ones
#end::info[]
#tag::paths[]
paths:
  #end::paths[]
  #tag::add[]
  /add:
    post: # <1>
      tags: [books]
      summary: Add a new book
      operationId: addBook
      requestBody: # <2>
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/BookInfo" # <3>
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
#end::add[]
#tag::components[]
components:
  schemas:
    BookInfo:
      title: Book Info # <1>
      description: Object containg all the info about a book
      type: object
      properties: # <2>
        name: {type: string}
        type:
          type: string
          enum:
            - BASIC
            - DETAILED
      required: ["name", "availability", "type"]
      discriminator:
        propertyName: type
        mapping:
          BASIC: "#/components/schemas/BasicBookInfo"
          DETAILED: "#/components/schemas/DetailedBookInfo"
    BasicBookInfo:
      x-all-of-name: BasicBookInfo
      allOf:
        - $ref: '#/components/schemas/BookInfo'
        - type: object
          properties: # <2>
            author: {type: string, minLength: 3}
          required: ["author"]
    DetailedBookInfo:
      x-all-of-name: DetailedBookInfo
      allOf:
        - $ref: '#/components/schemas/BookInfo'
        - type: object
          properties: # <2>
            author: {type: string, minLength: 3}
            isbn: {type: string, pattern: "[0-9]{13}"}
          required: ["author", "isbn"]
#end::components[]
